import { mySvnDays, svnPoppins } from "@/utils/fonts";
import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${svnPoppins.className} ${mySvnDays.variable} antialiased`}
      >
        <Header />
        <main className="mt-[140px] lg:mt-[175px]">
          {children}
        </main>
      </body>
    </html>
  );
}
