import { svnPoppins } from "@/utils/fonts";
import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${svnPoppins.className} antialiased`}
      >
        <Header />
        <main className="mt-[175px]">
          {children}
        </main>
      </body>
    </html>
  );
}
