import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { mySvnDays, svnPoppins } from "@/utils/fonts";
import type { Metadata } from "next";
import "./globals.css";
import Image from "next/image";
import leftCircle from "../assets/images/textures/blur-circle.svg";
import rightCircle from "../assets/images/textures/blur-circle-right.svg";

export const metadata: Metadata = {
  title: "Bidahub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${svnPoppins.className} ${mySvnDays.variable} antialiased relative`}
      >
        <div className="overflow-hidden relative">
          <Image src={leftCircle.src} width={639} height={639} alt="left circle texture" className="absolute top-[-2%] xl:top-[-5%] left-0 z-[1] w-[300px] xl:w-[639px]" />
          <Image src={rightCircle.src} width={639} height={639} alt="right circle texture" className="absolute top-[1%] md:top-[3%] xl:top-0 right-0 z-[1] w-[240px] md:w-[300px] xl:w-[639px]" />
          <Image src={leftCircle.src} width={639} height={639} alt="left circle texture" className="absolute top-[10%] md:top-[14%] -left-[4%] z-[1] w-[300px] xl:w-[639px]" />
          <Image src={rightCircle.src} width={520} height={520} alt="right circle texture" className="absolute top-[15%] md:top-[18%] right-0 z-[1] w-[300px] xl:w-[639px]" />
          <Image src={leftCircle.src} width={639} height={639} alt="left circle texture" className="absolute top-[22%] md:top-[42%] -left-[4%] z-[1]" />
          <Image src={rightCircle.src} width={520} height={520} alt="right circle texture" className="absolute top-[30%] md:top-[73%] right-0 z-[1]" />
          <Image src={leftCircle.src} width={520} height={520} alt="left circle texture" className="absolute top-[93%] -left-[10%] z-[1] w-[300px] xl:w-[520]" />
          <Image src={rightCircle.src} width={700} height={700} alt="right circle texture" className="absolute top-[98%] md:top-[96%] right-[0] z-[1] w-[340px] xl:w-[700px]" />
          <Header />
          <main className="pt-[140px] lg:pt-[175px] relative z-[2] overflow-hidden">
            <div className="relative z-[2]">
              {children}
            </div>
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
